language: python
python:
  - "2.7"
sudo: false
cache: pip
before_install:
  - pip install pytest pytest-cov codecov travis-sphinx guzzle_sphinx_theme
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest --cov=gftools --doctest-modules -v
  - travis-sphinx build 
after_success:
  - codecov
  - travis-sphinx deploy --branches=master,develope
notifications:
  email:
    on_success: never
    on_failure: always
git:
  depth: 5
