language: python
python:
  - "3.6"
sudo: false
cache: pip
before_install:
  - pip install 'pytest>=3.6' hypothesis pytest-cov codecov pydocstyle pyflakes 'attrs>=19.2.0'
  - pip install travis-sphinx numpydoc matplotlib sphinx_rtd_theme
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest --cov=gftools --doctest-modules -v
  - find gftools -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pydocstyle -v {} +
  - find gftools -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pyflakes {} +
  - travis-sphinx build
after_success:
  - codecov
  - travis-sphinx deploy --branches=master,develop
notifications:
  email:
    on_success: never
    on_failure: always
git:
  depth: 5
