language: python
python:
  - "2.7"
sudo: false
cache: pip
before_install:
  - pip install pytest pytest-cov codecov
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest --cov=gftools --doctest-modules -v
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
git:
  depth: 5
