language: python
python:
  - "3.6"
sudo: false
cache: pip
before_install:
  - pip install 'pytest>=3.6' 'hypothesis==4.24.5' pytest-cov codecov pydocstyle pyflakes hypothesis_gufunc 'attrs>=19.2.0' pylint
  - pip install travis-sphinx numpydoc matplotlib sphinx_rtd_theme
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  # - pytest --cov=gftool --doctest-modules -v
  - pytest --cov=gftool -v
  - find gftool -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pydocstyle -v {} +
  - find gftool -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pyflakes {} +
  - pylint --rcfile=.auto_pylintrc gftool
  - travis-sphinx build
  - sphinx-build -b doctest -d docs/build/doctrees   docs/source docs/build/doctest
after_success:
  - codecov
  - travis-sphinx deploy --branches=master,develop
notifications:
  email:
    on_success: never
    on_failure: always
git:
  depth: 5
