name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-dev.txt
          pip install -r requirements-doc.txt
          pip install -r requirements.txt
          python setup.py install
      - name: Basic Lint
        run: |
          find gftool -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pydocstyle -v {} +
          find gftool -name '*.py' -not -path '*/tests/*' -not -path '*.ropeproject*' -not -name _version.py -exec pyflakes {} +
      - name: Pylint
        run: pylint --rcfile=.auto_pylintrc gftool
      - name: Test code
        run: pytest --cov=gftool --cov-report=html -v
      - name: Test documentation
        run: |
          sphinx-build -d docs/build/doctrees docs/source docs/build/html
          sphinx-build -b doctest -d docs/build/doctrees docs/source docs/build/doctest
      - name: Coverage
        run: codecov
