name: Publish Python distributions to PyPI and TestPyPI

on:
  release:
    types:
      - published
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    if: github.repository == 'DerWeh/gftools'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build wheel twine
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Check built artifacts
      run: |
        python -m twine check dist/*
    - uses: actions/upload-artifact@v2
      with:
        name: releases
        path: dist

  test-built-dist:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.9
      - uses: actions/download-artifact@v2
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
      - name: Publish distribution to Test PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Check uploaded package
        if: github.event_name == 'push'
        run: |
          sleep 3
          python -m pip install --upgrade pip
          python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade gftool
          python -c "import gftool as gt; print(gt.__version__)"

  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
